//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : Administrator.java
//  @ Date : 2013-1-2
//  @ Author : 
//
//




public class Administrator extends PaltFormUser {
}
