//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : IPaltFormEntriy.java
//  @ Date : 2013-1-2
//  @ Author : 
//
//




public interface IPaltFormEntriy {
}
