//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : Member.java
<<<<<<< HEAD
//  @ Date : 2013-1-3
//  @ Author : windy
=======
//  @ Date : 2013-1-2
//  @ Author : 
>>>>>>> origin/master
//
//




<<<<<<< HEAD
public class Member extends SystemRole {
=======
public class Member extends PaltFormUser {
>>>>>>> origin/master
}
