//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : PaltFormUser.java
//  @ Date : 2013-1-2
//  @ Author : 
//
//




public abstract class PaltFormUser extends IPaltFormEntriy {
	protected Long uid;
	protected String username;
	protected Integer sex;
	protected String mobile;
	protected String note;
	protected Integer statu;
	protected String QQ;
	protected String mail;
	protected String password;
	protected String phone;
}
