//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : PlatformEntryUtil.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//




public class PlatformEntryUtil implements IPaltFormEntriy {
}
