//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : projectManager.java
<<<<<<< HEAD
//  @ Date : 2013-1-3
//  @ Author : windy
=======
//  @ Date : 2013-1-2
//  @ Author : 
>>>>>>> origin/master
//
//




<<<<<<< HEAD
/**
 * 项目经理用户类
**/
public class projectManager extends SystemRole {
=======
public class projectManager extends PaltFormUser {
>>>>>>> origin/master
}
