//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : SystemRole.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//




/**
 * 系统角色信息类
**/
public abstract class SystemRole extends PlatformEntryUtil {
	public Integer rid;
	public String roleName;
	public Integer status;
	public String description;
}
