//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : TeamLeader.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//




/**
 * 开发经理用户类
**/
public class TeamLeader extends SystemRole {
}
