//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : Administrator.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//



package com.amos.platform.common.entry;


/**
 * 最高管理员用户类
**/
public class Administrator extends SystemRole {
	

}
