package com.amos.platform.common.entry;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : IPaltFormEntriy.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//




/**
 * 系统实体公共接口，继承序列化接口，完成对象序列化工作。
**/
public  interface IPaltFormEntriy {
	/**
	 *
	 * @param    clzName  String clzName  完整类名（包括:包名，类名）
	 *                    格式xxx.xx.xx
	 *                    例子：amos.platform.common.SystemRole 
	**/
	public IPaltFormEntriy getEntryDetail(String clzName);
}
