//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : Member.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//



package com.amos.platform.common.entry;


public class Member extends SystemRole {
	/**
	 *
	 * @param    clzName  String clzName  完整类名（包括:包名，类名）
	 *                    格式xxx.xx.xx
	 *                    例子：amos.platform.common.SystemRole 
	**/
	
}
