//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : PaltFormUser.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//



package com.amos.platform.common.entry;

import java.util.List;


/**
 * 系统用户抽象类，定义系统用户数据结构
**/
public abstract class PaltFormUser extends PlatformEntryUtil {
	protected Long uid;
	protected String username;
	protected Integer sex;
	protected String mobile;
	protected String note;
	protected Integer statu;
	protected String QQ;
	protected String mail;
	protected String password;
	protected String phone;
	protected List<SystemRole> UserRoles;
	/**
	 *
	 * @param    clzName  String clzName  完整类名（包括:包名，类名）
	 *                    格式xxx.xx.xx
	 *                    例子：amos.platform.common.SystemRole 
	**/

}
