//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : PlatformEntryUtil.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//



package com.amos.platform.common.entry;


public class PlatformEntryUtil implements com.amos.platform.common.entry.IPaltFormEntriy {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5167992292515425044L;
	/**
	 *
	 * @param    clzName  String clzName  完整类名（包括:包名，类名）
	 *                    格式xxx.xx.xx
	 *                    例子：amos.platform.common.SystemRole 
	**/
	
	private IPaltFormEntriy entryDetail;
	
	public IPaltFormEntriy getEntryDetail(String clzName){
		
		return entryDetail;
	}
}
