//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : projectManager.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//



package com.amos.platform.common.entry;


/**
 * 项目经理用户类
**/
public class projectManager extends SystemRole {

	
}
