//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TeamServiceManager
//  @ File Name : SystemRole.java
//  @ Date : 2013-1-3
//  @ Author : windy
//
//



package com.amos.platform.common.entry;


/**
 * 系统角色信息类
**/
public abstract class SystemRole extends PlatformEntryUtil {
	public Integer rid;
	public String roleName;
	public Integer status;
	public String description;
	/**
	 *
	 * @param    clzName  String clzName  完整类名（包括:包名，类名）
	 *                    格式xxx.xx.xx
	 *                    例子：amos.platform.common.SystemRole 
	**/

}
